algoritmo "Multiplos de 10 ate 1000"
// Função :
// Autor :
// Data : 23/03/2016
// Seção de Declarações 

var

num : inteiro


inicio

Escreval(" -------------------------------------------------------------------")
Escreval("              EXERCICIO 1 - MULTIPLOS DE 10 ATE 1000")
Escreval(" -------------------------------------------------------------------")

num <- 10

enquanto (num <= 1000) faca

Escreval(num)
num <- num + 10

fimenquanto

fimalgoritmo
