algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2016
// Seção de Declarações 

//                             PARA TESTAR USE O COMANDO DE VALORES ALEATORIOS
var

cont : inteiro
contjogador : inteiro
idade : inteiro
peso : real
soma_peso_time : real
soma_peso_total : real
soma_idade_time : real
soma_idade_total : real
peso_medio_time  : real
idade_media_time : real
peso_medio_total : real
idade_media_total : real

time01 : caractere
time02 : caractere
time03 : caractere
time04 : caractere
time05 : caractere
time06 : caractere
time07 : caractere
time08 : caractere
time09 : caractere
time10 : caractere
time11 : caractere
time12 : caractere
time13 : caractere
time14 : caractere
time15 : caractere
time16 : caractere
time17 : caractere
time18 : caractere
time19 : caractere
time20 : caractere
time21 : caractere
time22 : caractere
time23 : caractere
time24 : caractere
time25 : caractere
time26 : caractere
time27 : caractere
time28 : caractere
time29 : caractere
time30 : caractere
time31 : caractere
time32 : caractere
time33 : caractere
time34 : caractere
time35 : caractere
time36 : caractere
time37 : caractere
time38 : caractere
time39 : caractere
time40 : caractere




inicio

cont<-1

repita

Escreval(" --------------------------------------------------------------------------------")
Escreval("                  EXERCICIO 10 - CAMPEONATO ENTRE TIMES DE FUTEBOL")
Escreval(" --------------------------------------------------------------------------------")

Escreval("")
Escreval("")


Escreval("                            CAMPEONATO DE FUTEBOL 2016")
Escreval("                                 CPD - Departament")

Escreval("")
Escreval("")

// INTERVALOS DO 1 AO 10 TIME PARA PEDIR O NOME
se((cont=1) ou (cont=25) ou (cont=49) ou (cont=73) ou (cont=97) ou (cont=121) ou (cont=145) ou (cont=169)  ou (cont=193) ou (cont=217))  entao

 contjogador <- 0

Escreval("                               Digite o nome do time")

Escreval("")
Escreval("")
Escreva("                                       ")


se ((cont=1)) entao
Leia(time01)

senao

se ((cont=25)) entao
Leia(time02)


senao

se ((cont=49)) entao
Leia(time03)

senao

se ((cont=73)) entao
Leia(time04)

senao

se ((cont=97)) entao
Leia(time05)

senao

se ((cont=121)) entao
Leia(time06)

senao
se ((cont=145)) entao
Leia(time07)

senao
se ((cont=169)) entao
Leia(time08)

senao
se ((cont=193)) entao
Leia(time09)

senao
se ((cont=217)) entao
Leia(time10)


fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse



// INTERVALOS DO 11 AO 20 TIME PARA PEDIR O NOME
se((cont=241) ou (cont=265) ou (cont=289)  ou (cont=313) ou (cont=337) ou (cont=361) ou (cont=385) ou (cont=409)  ou (cont=433) ou (cont=457)) entao

 contjogador <-0

Escreval("                               Digite o nome do time")

Escreval("")
Escreval("")
Escreva("                                       ")


se ((cont=241)) entao
Leia(time11)

senao
se ((cont=265)) entao
Leia(time12)

senao
se ((cont=289)) entao
Leia(time13)

senao
se ((cont=313)) entao
Leia(time14)

senao
se ((cont=337)) entao
Leia(time15)

senao
se ((cont=361)) entao
Leia(time16)

senao
se ((cont=385)) entao
Leia(time17)

senao
se ((cont=409)) entao
Leia(time18)

senao
se ((cont=433)) entao
Leia(time19)

senao
se ((cont=457)) entao
Leia(time20)

fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse


// INTERVALOS DO 21 AO 30 TIME PARA PEDIR O NOME
se((cont=481) ou (cont=505) ou (cont=529)  ou (cont=553) ou (cont=577) ou (cont=601) ou (cont=625) ou (cont=649)  ou (cont=673) ou  (cont=697)) entao

 contjogador <-0

Escreval("                               Digite o nome do time")

Escreval("")
Escreval("")
Escreva("                                       ")


senao
se ((cont=481)) entao
Leia(time21)

senao
se ((cont=505)) entao
Leia(time22)

senao
se ((cont=529)) entao
Leia(time23)

senao
se ((cont=553)) entao
Leia(time24)

senao
se ((cont=577)) entao
Leia(time25)

senao
se ((cont=601)) entao
Leia(time26)

senao
se ((cont=625)) entao
Leia(time27)

senao
se ((cont=649)) entao
Leia(time28)

senao
se ((cont=673)) entao
Leia(time29)

senao
se ((cont=697)) entao
Leia(time30)

fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse


// INTERVALOS DO 31 AO 40 TIME PARA PEDIR O NOME
se((cont=721) ou (cont=745) ou (cont=769)  ou (cont=793) ou (cont=817) ou (cont=841) ou (cont=865) ou (cont=889)  ou (cont=913)ou (cont=937)) entao

 contjogador <-0

Escreval("                               Digite o nome do time")

Escreval("")
Escreval("")
Escreva("                                       ")

se ((cont=721)) entao
Leia(time31)

senao
se ((cont=745)) entao
Leia(time32)

senao
se ((cont=769)) entao
Leia(time33)

senao
se ((cont=793)) entao
Leia(time34)

senao
se ((cont=817)) entao
Leia(time35)

senao
se ((cont=841)) entao
Leia(time36)

senao
se ((cont=865)) entao
Leia(time37)

senao
se ((cont=889)) entao
Leia(time38)

senao
se ((cont=913)) entao
Leia(time39)

senao
se ((cont=937)) entao
Leia(time40)

fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse

se (contjogador = 0) entao

soma_peso_time <- 0
soma_idade_time <- 0

fimse

//TIME 01
se (cont > 1) e (cont <=24) entao

contjogador <- contjogador+1

Escreval("                       -------------------------TIME 01-------------------------")
Escreval("                          TIME ", time01," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =24)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao

//TIME 02
se (cont > 25) e (cont <=48) entao


contjogador<- contjogador+1
Escreval("                       -------------------------TIME 02-------------------------")
Escreval("                          TIME ", time02," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =48)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 03
se (cont > 49) e (cont <=72) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 03-------------------------")
Escreval("                          TIME ", time03," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =72)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 04
se (cont > 73) e (cont <=96) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 04-------------------------")
Escreval("                          TIME ", time04," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =96)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 05
se (cont > 97) e (cont <=120) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 05-------------------------")
Escreval("                          TIME ", time05," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =120)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 06
se (cont > 121) e (cont <=144) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 06-------------------------")
Escreval("                          TIME ", time06," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =144)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 07
se (cont > 145) e (cont <=168) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 07-------------------------")
Escreval("                          TIME ", time07," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =168)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao
//TIME 08
se (cont > 169) e (cont <=192) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 08-------------------------")
Escreval("                          TIME ", time08," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =192)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 09
se (cont > 193) e (cont <=216) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 09-------------------------")
Escreval("                          TIME ", time09," - JOGADOR NUMERO ", contjogador )

Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =216)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 10
se (cont > 217) e (cont <=240) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 10-------------------------")
Escreval("                          TIME ", time10," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


        soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =240)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 11
se (cont > 241) e (cont <=264) entao

contjogador <- contjogador+1

Escreval("                       -------------------------TIME 11-------------------------")

Escreval("                          TIME ", time11," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =264)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao

//TIME 12
se (cont > 265) e (cont <=288) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 12-------------------------")
Escreval("                          TIME ", time12," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =288)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 13
se (cont > 289) e (cont <=312) entao

contjogador<- contjogador+1

Escreval("                       -------------------------TIME 13-------------------------")
Escreval("                          TIME ", time13," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =312)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 14
se (cont > 313) e (cont <=336) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 14-------------------------")
Escreval("                          TIME ", time14," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =336)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off


senao
//TIME 15
se (cont > 337) e (cont <=360) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 15-------------------------")
Escreval("                          TIME ", time15," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =360)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao
//TIME 16
se (cont > 361) e (cont <=384) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 16-------------------------")
Escreval("                          TIME ", time16," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =384)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 17
se (cont > 385) e (cont <=408) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 17-------------------------")
Escreval("                          TIME ", time17," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =408)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao
//TIME 18
se (cont > 409) e (cont <=432) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 18-------------------------")
Escreval("                          TIME ", time18," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

  soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =432)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 19
se (cont > 433) e (cont <=456) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 19-------------------------")
Escreval("                          TIME ", time19," - JOGADOR NUMERO ", contjogador )

Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =456)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 20
se (cont > 457) e (cont <=480) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 20-------------------------")
Escreval("                          TIME ", time20," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =480)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 21
se (cont > 481) e (cont <=504) entao

contjogador <- contjogador+1

Escreval("                       -------------------------TIME 21-------------------------")
Escreval("                          TIME ", time21," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =504)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao

//TIME 22
se (cont > 505) e (cont <=528) entao


contjogador<- contjogador+1
Escreval("                       -------------------------TIME 22-------------------------")
Escreval("                          TIME ", time22," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =528)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 23
se (cont > 529) e (cont <=552) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 23-------------------------")
Escreval("                          TIME ", time23," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =552)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 24
se (cont > 553) e (cont <=576) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 24-------------------------")
Escreval("                          TIME ", time24," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =576)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 25
se (cont > 577) e (cont <=600) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 25-------------------------")
Escreval("                          TIME ", time25," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =600)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 26
se (cont > 601) e (cont <=624) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 26-------------------------")
Escreval("                          TIME ", time26," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =624)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 27
se (cont > 625) e (cont <=648) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 27-------------------------")
Escreval("                          TIME ", time27," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =648)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 28
se (cont > 649) e (cont <=672) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 28-------------------------")
Escreval("                          TIME ", time28," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =672)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao
//TIME 29

se (cont > 673) e (cont <=696) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 29-------------------------")
Escreval("                          TIME ", time29," - JOGADOR NUMERO ", contjogador )

Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)
soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =696)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off


senao
//TIME 30
se (cont > 697) e (cont <=720) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 30-------------------------")
Escreval("                          TIME ", time30," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

 soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =720)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off


senao
//TIME 31
se (cont > 721) e (cont <=744) entao

contjogador <- contjogador+1

Escreval("                       -------------------------TIME 31-------------------------")

Escreval("                          TIME ", time31," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =744)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao

//TIME 32
se (cont > 745) e (cont <=768) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 32-------------------------")
Escreval("                          TIME ", time32," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)



soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =768)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
 
senao
//TIME 33
se (cont > 769) e (cont <=792) entao

contjogador<- contjogador+1

Escreval("                       -------------------------TIME 33-------------------------")
Escreval("                          TIME ", time33," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


senao
//TIME 34
se (cont > 793) e (cont <=816) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 34-------------------------")
Escreval("                          TIME ", time34," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =816)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 35
se (cont > 817) e (cont <=840) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 35-------------------------")
Escreval("                          TIME ", time35," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =840)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao
//TIME 36
se (cont > 841) e (cont <=864) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 36-------------------------")
Escreval("                          TIME ", time36," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =864)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 37
se (cont > 865) e (cont <=888) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 37-------------------------")
Escreval("                          TIME ", time37," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =888)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
senao
//TIME 38
se (cont > 889) e (cont <=912) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 38-------------------------")
Escreval("                          TIME ", time38," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

  soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =912)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 39
se (cont > 913) e (cont <=936) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 39-------------------------")
Escreval("                          TIME ", time39," - JOGADOR NUMERO ", contjogador )

Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)

soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =936)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off

senao
//TIME 40
se (cont > 937) e (cont <=960) entao

contjogador<- contjogador+1
Escreval("                       -------------------------TIME 40-------------------------")
Escreval("                          TIME ", time40," - JOGADOR NUMERO ", contjogador )

Escreval("")
Escreval("")

Escreval("                                    Digite a idade")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(idade)

Escreval("")
Escreval("")

Escreval("                                    Digite o peso")

Escreval("")
Escreval("")

Escreva("                                           ")
Leia(peso)


soma_peso_time <- soma_peso_time + peso
soma_idade_time <- soma_idade_time + idade

se (cont =960)  entao



peso_medio_time <- (soma_peso_time / contjogador)
idade_media_time <- (soma_idade_time/contjogador)

Escreval("")
Escreval ("O  peso Medio do time é: ",(peso_medio_time):1:2)
Escreval ("A idade Media do time é: ", (idade_media_time):1:2)

timer (3000) on
fimse

 timer (0) off
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse

soma_idade_total <- soma_idade_total + idade
soma_peso_total <- soma_peso_total + peso

cont <- cont+1
limpatela
ate (cont>=961)

Escreval(" --------------------------------------------------------------------------------")
Escreval("                  EXERCICIO 10 - CAMPEONATO ENTRE TIMES DE FUTEBOL")
Escreval(" --------------------------------------------------------------------------------")

Escreval("")
Escreval("")


Escreval("                            CAMPEONATO DE FUTEBOL 2016")
Escreval("                                 CPD - Departament")


Escreval("")
Escreval("")


peso_medio_total <- (soma_peso_total/(40*23))
idade_media_total <- (soma_idade_total/(40*23))

Escreval ("O  peso Medio dos participantes é: ",(peso_medio_total):1:2)
Escreval ("A idade Media dos participantes é:", (idade_media_total):1:2)





fimalgoritmo
